version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres:14.0-alpine
    container_name: postgres-shopping-cart-service
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
